spring:
  application:
    name: StudentManagementSystem
    security:
      jwt:
        secret_key: "TXlTdXBlclNlY3JldEtleUNyYWNrTWVJZllvdUNhbkl0SXNBVmVyeUxvbmdLZXlYRHhEeERIYUhhSGEK"
        expiration: 3600
        refresh_expiration: 86400
  datasource:
    url: jdbc:postgresql://192.168.1.3:15432/student-mgt
    username: postgres
    password: Pg@2024
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect